  steps:
      - name: node:10.15.1
        dir: functions
        entrypoint: npm
        args: [ 'install' ]
      - name: node:10.15.1
        dir: functions
        entrypoint: npm
        args: [ 'test' ]
      - name: node:10.15.1
        dir: functions
        entrypoint: npm
        args: [ 'run', 'build.prod' ]
      - name: 'gcr.io/dev-alpha/firebase'
        args: [ 'deploy', '-P', 'js-demo-fe-staging']
