steps:
  - id: 'Install npm packages'
    dir: 'functions'
    name: 'node:12.9-buster'
    args: ['npm', 'install']
  - id: "Deploy to Firebase"
    name: 'gcr.io/local-22c4a/firebase'
    args: ['deploy']
    