name: Build and Deploy
on:
  push:
    paths:
      - 'staging/**'
    branches:
      - test-branch
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: copy staging repo
        run: mv ./staging/* ./
      - name: show staging repo
        run: ls -a ./
      - name: Install Dependencies
        run: npm ci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: 'deploy'
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
