name: Build and Deploy
on:
  push:
    branches:
      - test-branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: functions
        run: npm ci
      - name: Build
        working-directory: functions
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: functions/public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: functions/public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibG9jYWwtMjJjNGEiLAogICJwcml2YXRlX2tleV9pZCI6ICJlZTJmZTM0Yjg0OWZlYTk1MmViZTk4Zjk0NjZjNjNiN2JjYjY0NTE4IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUMvR1F2M3JJNmNrR3U3XG5UK0lNeHFRaTd2MHg4Sm5pUWVPL2pZOG1CNkpydURqVWk0SDNyamxJdFpHbmRqZU9JVVV0dEdLbThveDRaNXA1XG5LQVBsd3pVanE1QThibDVqS0lLckV1ZUMwQTZDbnNhV2lmUUNOcnRPbDN5MTBaK1hITVV1NjlqaSs5VTFmQnEyXG5xcW05Q3k5Qkc5VFVPWWVIRHhYWnorVW11Yk84d25DcjgzNUNTS3pnRWRrTDV1ZS9nN2R5S0tlR3ZlZktwTDkrXG5JYTM2WjluNTRVaXQySU10amlDaXFpN1lybWpCcUVYVG4ySnRHa3lLaVUva2RjZkNCd2ZMVE5LOWVLTmE5NTV5XG4xNGthVXdWQ1ZwQjhuUEdlWlhERUpoNUI3ZWJPSGRjTjljV1UyRTR6ejdtanlhemJFdVFNWlhBWWpPZWsyNlhmXG5BcUd4WGRXZEFnTUJBQUVDZ2dFQUdhMWQ1RXUxWmVncDhhTk1ObmRDZXNjdUVsWEg5NVR1NjBBMEtlSUF1d1NuXG43amRJb1dVeG9VbDBadElGcVAxamRENjJ1c1FBaC9VejFtL0FCbEZ5aEhaN0RRT3ZmeGRrWjJSRTQxamRla09uXG5YM2J0NkpZK0dOTldHSUF3TjNmUUx2dlZ5cm9YN2ZYZENRcHBnRk5PYUNzN0w4RURLdXlsL1B4b1NBblAwdDc2XG5JQzZ4N3I2YnhmWlF4V3JYdHRVOUhSeWZBNUxsdEp6RFBlUzY0VUxwSUtCRjBza0xYWTBXbkNYelhZNHZCQ21QXG5NMUhDMXp1T0FHZU9JQVRGSXZpdFM3RENYZ3lPSkY1SW5YZEVUQUU3d1lrRGRCWXZaUWk3K1J4R3JBQmZLN3IwXG5xMkkrWG92aUNoMmtqWlBWeE9ZcHhMTHFIZ1g0SkZYU3poT3pOZ2RYcVFLQmdRRGRaSUprTi91MnZPWE9ITnJ0XG5aYlRZQTB3S05kNnVuZTZRVWZvOUxjaW8xeDFka0piRldqdE45WWFaeXdDZ2FKL3cvT2xLS1pLcnlGWlo3OEQrXG5xa2lXN24vaC9mN204ZVFyUTgwZU9uRHRCUDNocWJFazRzV0oyMEZHUngzakN5aE1vRWRqUFZHTGo4c1NaRWJYXG54U3lENzZGU21IWHJmZW1OL29jbWQ5cXZwd0tCZ1FEYytEcHgyZWtkeGhWMlZJUWYrbTFlc2pLNExBTXRHR2dMXG5vT2VGRjFjelc5SDV5eUtEeUVOcEhNRnp6M3JWWEkvKzRRaGNmbXFVUWx0NGNIY0JRLzdheVhBSERSR0tKaFYwXG4wYXIwZGNtUXpkMlJNcE5TaW02K0dUUHNZU3VydXpqNVdwV0JxRll4enY2V1N4SHdjdnpNaGNCQkRseDF4dFp4XG5UVzBWTVdvWkd3S0JnUUNDajdpWjA2NGRPVThvK3psYzBTTVNWUGR0K2hEbDEzdU9IdG85WkJlM0FvMXQxVXdrXG4vSzZHcmluLzNvanpFR0JxWlN4TE1UTXZIVWxYWnAzaFVaalhjYlYzR0N4UUZBemtPdXJuVGIyMCtjR2phRWh3XG5vVSt2bWQ3bnpCN2krM3g3bS9ZZG4xYk13RE1aR0l2eXlYUVVKcWh6cGplOGRoZmJSbVI3bWlrY2R3S0JnQkhtXG5kZTJWSm9KSDhxTWtVNU8zbUxhTUh2bTJid2R2SzdhTmNWUGh3U21pN1k2YnV3OEw0UklaeHo0WGQ2N2pFYk1uXG5EYU5ZaGsrK1ZHU2NUN2VsaDNhM3pNQjFlWTlFYUlhUEdaYzJGMzhJZmtOdDRtdFVWWVpHeW1NQ3VDUHdSYnhGXG5iMGtTbHZEd0FNV3lEU0Q2WDZvOXg0WTlvSlhWNXJkRSsybzFGNUF6QW9HQVQveHI5cFh3eWR5UGs5S29ZR3FIXG5DZ2NTaE5KQUkyUytEQ3BxVit2SGgveW8vTDJCazkvTXRtZDNRd2IxR3lsQitLM1V4VW9QNnFjSGtpOHRsVUVMXG5EUS9kbks3VTlzQzFnNVJYVG5YWjFHcFRGYmM4cUVUc09LY0hJbFpuTUVZdWtsQ2J2MEdQVkwwRFJJSFV5ZWFTXG44bThLa0xBeXRLS3hiRGxYQ1E0bjkrdz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJkZXBsb3lAbG9jYWwtMjJjNGEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE3Mjg1NTIwMjE4Mzg1MDU4Nzg0IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kZXBsb3klNDBsb2NhbC0yMmM0YS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
          PROJECT_ID: "local--22c4a"
